services:
  - type: web
    name: chocudan24h
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: APP_URL
        value: https://chocudan24h.com
